server:
  port: "8080"

db:
  dsn: "root:root@tcp(localhost:13306)/smart_community?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"

minio:
  endpoint: "42.193.104.173:9000"
  access_key: "admin"
  secret_key: "12345678"
  bucket: "community"
  use_ssl: false

ai:
  api_key: "sk-3afaa00674244df6b483dcf36272997f"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
  model: "qwen-plus"

facebody:
  access_key_id: ""
  access_key_secret: ""
  endpoint: "facebody.cn-shanghai.aliyuncs.com"
